
server:
  port: 8000

spring:
  application:
    name: service-api-gateway
  cloud:
    gateway:
      routes:
        - id: server-notification
          uri: http://localhost:8001
          predicates:
            - Path=/notification/**
          filters:
            - RewritePath=/notification/(?<remaining>.*), /$\{remaining}

        - id: server-discovery
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
          filters:
            - RewritePath=/eureka/(?<remaining>.*), /$\{remaining}

logging:
  level:
    org:
      springframework:
        cloud:
          config: DEBUG
